version: '1.0'
name: master-pipeline
displayName: MasterPipeline
stages:
  - stage: 
    name: compile
    displayName: Compile
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs Build
        # 支持8.16.2、10.17.0、12.16.1、14.16.0、15.12.0五个版本
        nodeVersion: 14.16.0
        # Build命令：安装依赖 -> 清除上次打包产物残留 -> 执行Build 【请根据项目实际产出进行填写】
        commands:
          - npm install && rm -rf ./dist && npm run build
        # 非必填字段，开启后表示将Build产物暂存，但不会上传到制品库中，7天后自动清除
        artifacts:
            # Build产物名字，作为产物的唯一标识可向下传递，支持自定义，默认为BUILD_ARTIFACT。在下游可以通过${BUILD_ARTIFACT}方式引用来获取Build物地址
          - name: BUILD_ARTIFACT
            # Build产物获取路径，是指代码Compile完毕之后Build物的所在路径
            path:
              - ./dist
      - step: publish@general_artifacts
        name: publish_general_artifacts
        displayName: Upload Artifact
        # 上游Build任务定义的产物名，默认BUILD_ARTIFACT
        dependArtifact: BUILD_ARTIFACT
        # 上传到制品库时的制品命名，默认output
        artifactName: output
        dependsOn: build_nodejs
  - stage: 
    name: release
    displayName: Publish
    steps:
      - step: publish@release_artifacts
        name: publish_release_artifacts
        displayName: 'Publish'
        # 上游Upload Artifact任务的产出
        dependArtifact: output
        # Publish制品版本号
        version: '1.0.0.0'
        # 是否开启版本号自增，默认开启
        autoIncrement: true
triggers:
  push:
    branches:
      include:
        - master
