name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Alibaba Cloud Container Registry
        run: |
          echo "${{ secrets.ACR_USERNAME }}" | docker login --username ${{ secrets.ACR_USERNAME }} --password ${{ secrets.ACR_PASSWORD }} ${{ secrets.ACR_REGISTRY }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.ACR_REGISTRY }}/shilohl/big-market-front:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.ACR_REGISTRY }}/shilohl/big-market-front:latest
